# Generated by Django 3.2.12 on 2023-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230511_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
