# Generated by Django 3.2.12 on 2023-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_cadastro_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nome',
        ),
    ]
