# Generated by Django 3.2.12 on 2023-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_cadastro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
